-- Insert sample professions
INSERT INTO professions (name, description) VALUES
  ('Physiotherapist', 'Physical therapy professional'),
  ('Nutritionist', 'Nutrition and dietetics professional'),
  ('Pharmacist', 'Pharmacy professional'),
  ('Nurse', 'Nursing professional'),
  ('Medical Lab Technician', 'Laboratory professional'),
  ('Doctor', 'Medical doctor / physician'),
  ('Dentist', 'Dental health professional'),
  ('Radiologist', 'Medical imaging professional'),
  ('Medical Imaging Technologist', 'Imaging technologist (Radiography, CT, MRI, Ultrasound, etc.)'),
  ('Anesthesiologist', 'Anesthesia specialist'),
  ('Cardiologist', 'Heart specialist'),
  ('Dermatologist', 'Skin specialist'),
  ('Endocrinologist', 'Hormones & metabolism specialist'),
  ('Gastroenterologist', 'Digestive system specialist'),
  ('General Surgeon', 'Surgical specialist'),
  ('Gynecologist', 'Women''s reproductive health specialist'),
  ('Hematologist', 'Blood specialist'),
  ('Neurologist', 'Nervous system specialist'),
  ('Nephrologist', 'Kidney specialist'),
  ('Oncologist', 'Cancer specialist'),
  ('Ophthalmologist', 'Eye specialist'),
  ('Orthopedic Surgeon', 'Bone & musculoskeletal specialist'),
  ('Pediatrician', 'Child specialist'),
  ('Psychiatrist', 'Mental health specialist'),
  ('Pulmonologist', 'Lung & respiratory specialist'),
  ('Rheumatologist', 'Joints/autoimmune disease specialist'),
  ('Urologist', 'Urinary tract & male reproductive health'),
  ('Emergency Medicine Physician', 'Acute care specialist'),
  ('Family Medicine Physician', 'Primary care specialist'),
  ('Internal Medicine Physician', 'General medicine specialist'),
  ('Obstetrician', 'Pregnancy and childbirth specialist'),
  ('ENT Specialist', 'Ear, nose, and throat specialist'),
  ('Pathologist', 'Disease diagnosis (lab) specialist'),
  ('Physician Assistant', 'Medical care provider'),
  ('Occupational Therapist', 'Daily living skills therapist'),
  ('Speech Therapist', 'Speech/language therapist'),
  ('Optometrist', 'Vision specialist'),
  ('Audiologist', 'Hearing/balance specialist'),
  ('Respiratory Therapist', 'Respiratory care'),
  ('Orthotist', 'Brace specialist'),
  ('Prosthetist', 'Artificial limb specialist'),
  ('Chiropractor', 'Spinal health professional'),
  ('Podiatrist', 'Foot & ankle specialist'),
  ('Genetic Counselor', 'Hereditary disease advisor'),
  ('Midwife', 'Pregnancy, birthing & postpartum care'),
  ('Occupational Health Specialist', 'Workplace safety and health'),
  ('Paramedic', 'Emergency medical response'),
  ('Medical Technologist', 'Lab diagnostic specialist'),
  ('Biostatistician', 'Health data specialist'),
  ('Medical Social Worker', 'Patient social support'),
  ('Clinical Psychologist', 'Psychological assessment/intervention')
ON CONFLICT (name) DO NOTHING;

-- Insert sample health authorities
INSERT INTO health_authorities (name, country) VALUES
  ('Dubai Health Authority', 'UAE'),
  ('Abu Dhabi Department of Health', 'UAE'),
  ('Saudi Commission for Health Specialties', 'Saudi Arabia'),
  ('Qatar Council for Healthcare Practitioners', 'Qatar'),
  ('Kuwait Ministry of Health', 'Kuwait')
ON CONFLICT (name) DO NOTHING;
