-- Applicant intro reels (paid add-on) + storage policies

-- 1) Extend entitlements to support add-ons (e.g. REELS)
ALTER TABLE user_entitlements
  ADD COLUMN IF NOT EXISTS addon_code VARCHAR(32);

-- Expand scope check to include ADDON (constraint name is autogenerated in some environments)
ALTER TABLE user_entitlements
  DROP CONSTRAINT IF EXISTS user_entitlements_scope_check;

ALTER TABLE user_entitlements
  ADD CONSTRAINT user_entitlements_scope_check
  CHECK (scope IN ('PACKAGE', 'EXAM', 'ADDON'));

-- Update target constraint to support addon_code
ALTER TABLE user_entitlements
  DROP CONSTRAINT IF EXISTS entitlement_target_required;

ALTER TABLE user_entitlements
  ADD CONSTRAINT entitlement_target_required CHECK (
    (scope = 'PACKAGE' AND package_id IS NOT NULL AND exam_id IS NULL AND addon_code IS NULL)
    OR
    (scope = 'EXAM' AND exam_id IS NOT NULL AND package_id IS NULL AND addon_code IS NULL)
    OR
    (scope = 'ADDON' AND addon_code IS NOT NULL AND package_id IS NULL AND exam_id IS NULL)
  );

CREATE INDEX IF NOT EXISTS idx_user_entitlements_addon_code
  ON user_entitlements(addon_code);

-- 2) Applicant reels metadata
CREATE TABLE IF NOT EXISTS applicant_reels (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
  status VARCHAR(16) NOT NULL DEFAULT 'DRAFT'
    CHECK (status IN ('DRAFT', 'PUBLISHED', 'HIDDEN')),
  visibility VARCHAR(16) NOT NULL DEFAULT 'PUBLIC'
    CHECK (visibility IN ('PUBLIC', 'APPLY_ONLY')),
  caption TEXT,
  tags JSONB NOT NULL DEFAULT '[]'::jsonb,
  video_path TEXT,
  thumbnail_path TEXT,
  duration_seconds INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_applicant_reels_user_id
  ON applicant_reels(user_id);

CREATE INDEX IF NOT EXISTS idx_applicant_reels_status_visibility
  ON applicant_reels(status, visibility);

CREATE TRIGGER update_applicant_reels_updated_at
  BEFORE UPDATE ON applicant_reels
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 3) Reels analytics events (optional; used for ranking later)
CREATE TABLE IF NOT EXISTS applicant_reel_events (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  reel_id UUID NOT NULL REFERENCES applicant_reels(id) ON DELETE CASCADE,
  viewer_user_id UUID REFERENCES user_profiles(id) ON DELETE SET NULL,
  event_type VARCHAR(32) NOT NULL
    CHECK (event_type IN ('VIEW', 'CLICK', 'WATCH_PROGRESS', 'APPLY_FROM_REEL')),
  watch_ms INTEGER,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_applicant_reel_events_reel_id_created_at
  ON applicant_reel_events(reel_id, created_at DESC);

-- 4) RLS
ALTER TABLE applicant_reels ENABLE ROW LEVEL SECURITY;
ALTER TABLE applicant_reel_events ENABLE ROW LEVEL SECURITY;

-- Applicant reels: users manage their own
DROP POLICY IF EXISTS "Reels: users insert own" ON applicant_reels;
CREATE POLICY "Reels: users insert own"
  ON applicant_reels FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Reels: users select own" ON applicant_reels;
CREATE POLICY "Reels: users select own"
  ON applicant_reels FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Reels: users update own" ON applicant_reels;
CREATE POLICY "Reels: users update own"
  ON applicant_reels FOR UPDATE TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Reels: users delete own" ON applicant_reels;
CREATE POLICY "Reels: users delete own"
  ON applicant_reels FOR DELETE TO authenticated
  USING (auth.uid() = user_id);

-- Applicant reels: authenticated users can view published PUBLIC reels (employer search/feed use-case)
DROP POLICY IF EXISTS "Reels: authenticated view published public" ON applicant_reels;
CREATE POLICY "Reels: authenticated view published public"
  ON applicant_reels FOR SELECT TO authenticated
  USING (status = 'PUBLISHED' AND visibility = 'PUBLIC');

-- Applicant reels: admins full access
DROP POLICY IF EXISTS "Reels: admins manage all" ON applicant_reels;
CREATE POLICY "Reels: admins manage all"
  ON applicant_reels FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE user_profiles.id = auth.uid() AND user_profiles.role = 'ADMIN'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE user_profiles.id = auth.uid() AND user_profiles.role = 'ADMIN'
    )
  );

-- Events: authenticated users insert their own viewing events (viewer_user_id must match)
DROP POLICY IF EXISTS "Reel events: insert own" ON applicant_reel_events;
CREATE POLICY "Reel events: insert own"
  ON applicant_reel_events FOR INSERT TO authenticated
  WITH CHECK (viewer_user_id = auth.uid());

-- Events: admins select all
DROP POLICY IF EXISTS "Reel events: admins select all" ON applicant_reel_events;
CREATE POLICY "Reel events: admins select all"
  ON applicant_reel_events FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE user_profiles.id = auth.uid() AND user_profiles.role = 'ADMIN'
    )
  );

-- 5) Storage bucket + policies
-- Private bucket: applicant reels (paths: {user_id}/{reel_id}/...)
INSERT INTO storage.buckets (id, name, public)
VALUES ('applicant-reels', 'applicant-reels', false)
ON CONFLICT (id) DO NOTHING;

-- Upload only under own folder
DROP POLICY IF EXISTS "Applicant reels: users upload under own user id folder" ON storage.objects;
CREATE POLICY "Applicant reels: users upload under own user id folder"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'applicant-reels'
    AND split_part(name, '/', 1) = auth.uid()::text
  );

-- Owner reads their own uploads
DROP POLICY IF EXISTS "Applicant reels: users read own uploads" ON storage.objects;
CREATE POLICY "Applicant reels: users read own uploads"
  ON storage.objects FOR SELECT TO authenticated
  USING (
    bucket_id = 'applicant-reels'
    AND split_part(name, '/', 1) = auth.uid()::text
  );

-- Authenticated reads published PUBLIC reels' assets
DROP POLICY IF EXISTS "Applicant reels: authenticated read published public assets" ON storage.objects;
CREATE POLICY "Applicant reels: authenticated read published public assets"
  ON storage.objects FOR SELECT TO authenticated
  USING (
    bucket_id = 'applicant-reels'
    AND EXISTS (
      SELECT 1
      FROM applicant_reels r
      WHERE (r.video_path = storage.objects.name OR r.thumbnail_path = storage.objects.name)
        AND r.status = 'PUBLISHED'
        AND r.visibility = 'PUBLIC'
    )
  );

-- Owner deletes their own uploads
DROP POLICY IF EXISTS "Applicant reels: users delete own uploads" ON storage.objects;
CREATE POLICY "Applicant reels: users delete own uploads"
  ON storage.objects FOR DELETE TO authenticated
  USING (
    bucket_id = 'applicant-reels'
    AND split_part(name, '/', 1) = auth.uid()::text
  );

-- Admins read all reel objects
DROP POLICY IF EXISTS "Applicant reels: admins read all" ON storage.objects;
CREATE POLICY "Applicant reels: admins read all"
  ON storage.objects FOR SELECT TO authenticated
  USING (
    bucket_id = 'applicant-reels'
    AND EXISTS (
      SELECT 1 FROM user_profiles
      WHERE user_profiles.id = auth.uid() AND user_profiles.role = 'ADMIN'
    )
  );

